### ISSUE TITLE
Got an AttributeError on version 0.2.1

### ISSUE THREAD

**Issue by MiCHiLU** [ktok07b6/polyphony#3] opened 2017-02-10 01:43 UTC
```
Traceback (most recent call last):
  File "/Users/<user>/.virtualenvs/polyphony/bin/polyphony", line 4, in <module>
    main()
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/__main__.py", line 395, in main
    compile_main(src_file, options.output_name, options.output_dir, options.debug_mode)
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/__main__.py", line 309, in compile_main
    IRTranslator().translate(read_source(src_file))
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/irtranslator.py", line 811, in translate
    visitor.visit(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/irtranslator.py", line 196, in visit_FunctionDef
    self.visit(stm)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/irtranslator.py", line 241, in visit_Return
    self.emit(MOVE(ret, self.visit(node.value)), node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/<user>/.virtualenvs/polyphony/lib/python3.6/site-packages/polyphony/compiler/irtranslator.py", line 642, in visit_Call
    if node.starargs:
AttributeError: 'Call' object has no attribute 'starargs'
```

It does not have the problem on version 0.2.0.

**Comment by ktok07b6** [comment] 2017-02-10 04:54
This should be fixed now. Thanks for reporting the problem!
It's caused by a specific Python version (probably Python 3.5 or later).

**Closed by ktok07b6** 2017-02-10 04:54 UTC
